#define BOOST_TEST_MODULE "All CPP Tests"
#include <boost/test/included/unit_test.hpp>

#include "geometry_test.cpp"
#include "range_support_test.cpp"
#include "array_helper_test.cpp"
#include "linear_algebra_test.cpp"
#include "sorted_list_test.cpp"
////#include "BDPropagator_test.cpp"
#include "MatrixSpace_test.cpp"
#include "SphericalBesselGenerator_test.cpp"
//#include "BDSimulator_test.cpp"
#include "MatrixSpaceWithCylinders_test.cpp"
#include "SphericalBesselTable_test.cpp"
//#include "CylindricalBesselGenerator_test.cpp"
////#include "model_test.cpp"
////#include "StructureUtils_test.cpp"
#include "DynamicPriorityQueue_test.cpp"
#include "pointer_as_ref_test.cpp"
#include "Vector3_test.cpp"
////#include "EGFRDSimulator_test.cpp"
#include "position_test.cpp"
//#include "World_test.cpp"
